"""criacao inicial das tabelas

Revision ID: f33644e866c5
Revises: 
Create Date: 2026-04-08 21:47:47.610747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33644e866c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cronometro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(), nullable=True),
    sa.Column('duracao_segundos', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('pausado_em', sa.DateTime(), nullable=True),
    sa.Column('segundos_pausados', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cronometro_id'), 'cronometro', ['id'], unique=False)
    op.create_table('dossies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_desaparecimento', sa.Date(), nullable=False),
    sa.Column('local', sa.String(length=200), nullable=False),
    sa.Column('coordenadas', sa.String(length=50), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossies_id'), 'dossies', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('is_avaliador', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_login'), 'usuarios', ['login'], unique=True)
    op.create_table('arquivos_dossie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossie_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('url_s3', sa.String(length=500), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossie_id'], ['dossies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arquivos_dossie_id'), 'arquivos_dossie', ['id'], unique=False)
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('avaliador_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['avaliador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_id'), 'grupos', ['id'], unique=False)
    op.create_table('membros_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membros_grupo_id'), 'membros_grupo', ['id'], unique=False)
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('is_avaliador', sa.Boolean(), nullable=False),
    sa.Column('is_sistema', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_id'), 'mensagens', ['id'], unique=False)
    op.create_table('respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('dossie_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('comentario_avaliacao', sa.Text(), nullable=True),
    sa.Column('categoria_original', sa.String(length=50), nullable=True),
    sa.Column('categoria_nova', sa.String(length=50), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('avaliado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dossie_id'], ['dossies.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respostas_id'), 'respostas', ['id'], unique=False)
    op.create_table('arquivos_resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resposta_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('url_s3', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['resposta_id'], ['respostas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arquivos_resposta_id'), 'arquivos_resposta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arquivos_resposta_id'), table_name='arquivos_resposta')
    op.drop_table('arquivos_resposta')
    op.drop_index(op.f('ix_respostas_id'), table_name='respostas')
    op.drop_table('respostas')
    op.drop_index(op.f('ix_mensagens_id'), table_name='mensagens')
    op.drop_table('mensagens')
    op.drop_index(op.f('ix_membros_grupo_id'), table_name='membros_grupo')
    op.drop_table('membros_grupo')
    op.drop_index(op.f('ix_grupos_id'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_arquivos_dossie_id'), table_name='arquivos_dossie')
    op.drop_table('arquivos_dossie')
    op.drop_index(op.f('ix_usuarios_login'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_dossies_id'), table_name='dossies')
    op.drop_table('dossies')
    op.drop_index(op.f('ix_cronometro_id'), table_name='cronometro')
    op.drop_table('cronometro')
    # ### end Alembic commands ###
